#!/bin/bash

echo "🤖 Jarvis Command Help Menu"
echo "────────────────────────────────────────────"
echo "Your Offline AI Assistant - Local LLM Setup"
echo ""
echo "🧠 Text Mode:"
echo "  jarvis             → Launch Jarvis in terminal (text-only, offline ChatGPT style)"
echo "  unjarvis           → Stops Jarvis if it's running in background or taking memory"
echo ""
echo "🎙️ Voice Mode:"
echo "  vjarvis            → Launch voice-activated Jarvis with speech-to-text and TTS"
echo ""
echo "🔧 Maintenance:"
echo "  jarvis-diagnostics → Check Jarvis system status (RAM, models, GPU use, etc.)"
echo "  ollama list        → View installed LLM models"
echo "  ollama run <model> → Test specific model manually"
echo ""
echo "🗃️ Files & Models:"
echo "  ~/jarvis/Modelfile              → Jarvis persona settings"
echo "  ~/.local/share/piper/models/en → Voice models for Piper"
echo ""
echo "🔁 Update Ollama:"
echo "  curl -fsSL https://ollama.com/install.sh | sh"
echo ""
echo "📝 Developer Notes:"
echo "  - Whisper handles voice recognition"
echo "  - Piper handles voice responses"
echo "  - Mistral LLM is used by default in text & voice"
echo ""
echo "📁 All scripts live in: ~/jarvis/"
echo "────────────────────────────────────────────"
echo "Jarvis at your service, Sir Maverick. 🧠🛠️"
